apiVersion: apps/v1
kind: Deployment
metadata:
  name: web # Название нашего объекта Deployment
spec:
  replicas: 3 # Начнем с одного пода
  selector: # Укажем, какие поды относятся к нашему Deployment:
    matchLabels: # - это поды с меткой
      app: web # app и ее значением web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template: # Теперь зададим шаблон конфигурации пода
    metadata:
      name: web
      labels:
        app: web
    spec:
      containers:
      - name: mhttpd
        image: nioliz/myhttpd
        readinessProbe: # Добавим проверку готовности
          #          httpGet: # веб-сервера отдавать
          #            path: /index.html # контент
          #            port: 8000
          tcpSocket: { port: 8000 }
        volumeMounts:
          - name: app
            mountPath: /app
      initContainers:
      - name: init
        image: busybox
        command: ['sh', '-c', 'wget --no-check-certificate -O- https://gist.githubusercontent.com/Konstantinov86/3364e7f98124f7f183a2b4a5bb812d4d/raw/fbc5c6b5465981ed56dc7ecc454c72148e8e85d3/otus-k8s-intro | sh']
        volumeMounts:
          - name: app
            mountPath: /app
      volumes:
      - name: app
        emptyDir: {}
    
