---
apiVersion: v1
kind: ServiceAccount
metadata: 
  name: bob
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bob-admin-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: bob
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dave
