apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web
  labels:
    app: paymentService
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentService
  template:
    metadata:
      labels:
        app: paymentService
    spec:
      containers:
      - name: mhttpd
        image: nioliz/myhttpd:v0.0.1
        resources: {}
        volumeMounts:
        - name: app
          mountPath: /app
      initContainers:
      - name: init
        image: busybox
        command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
        volumeMounts:
          - name: app
            mountPath: /app
      volumes:
      - name: app
        emptyDir: {}

